
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int AND = 27;
  public static final int MENOS = 4;
  public static final int LT = 17;
  public static final int CLASS = 29;
  public static final int ELSE = 22;
  public static final int SEMICOLON = 14;
  public static final int INT = 30;
  public static final int OR = 28;
  public static final int RBRACE = 12;
  public static final int RPAREN = 8;
  public static final int SEMI = 2;
  public static final int NOT = 26;
  public static final int RETURN = 23;
  public static final int TRUE = 24;
  public static final int IF = 21;
  public static final int GT = 18;
  public static final int LPAREN = 7;
  public static final int LBRACE = 11;
  public static final int ID = 9;
  public static final int ATRIB = 10;
  public static final int MAIS = 3;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int MENOSUNIT = 6;
  public static final int FALSE = 25;
  public static final int NUMERO = 31;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int EQ = 16;
  public static final int BOOL = 19;
  public static final int VEZES = 5;
  public static final int VOID = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "MAIS",
  "MENOS",
  "VEZES",
  "MENOSUNIT",
  "LPAREN",
  "RPAREN",
  "ID",
  "ATRIB",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "SEMICOLON",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "BOOL",
  "VOID",
  "IF",
  "ELSE",
  "RETURN",
  "TRUE",
  "FALSE",
  "NOT",
  "AND",
  "OR",
  "CLASS",
  "INT",
  "NUMERO"
  };
}

